name: generate readme

on:
  schedule:
    - cron: '0 0 */1 * *'

  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  readme:
    name: generate readme
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/develop' && !contains(github.event.head_commit.message, 'ci skip')
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
    steps:
      - name: check out a copy of the repo
        uses: actions/checkout@v2

      - name: generate readme
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          template: 'provision/templates/README.md.tpl'
          writeTo: 'README.md'

      - name: commit readme
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          commit_message: 'build: update readme ci skip'
          branch: develop
          commit_options: '--no-verify --signoff'
          commit_user_name: '@slovacus'
          commit_user_email: 'slovacus@gmail.com'
          commit_author: 'slovacus <slovacus@gmail.com>'
