name: generate readme

on:
  schedule:
    - cron: "0 0 */1 * *"

  pull_request:
    branches:
      - develop

jobs:
  readme:
    name: generate readme
    runs-on: ubuntu-20.04
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
    steps:

      - name: check out a copy of the repo
        uses: actions/checkout@v2

      - name: generate readme
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
        with:
          template: "provision/templates/README.md.tpl"
          writeTo: "README.md"

      - name: commit resume pdf
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
        with:
          commit_message: 'build: update generated readme'
          branch: develop
          commit_options: '--no-verify --signoff'
          commit_user_name: "@slovacus"
          commit_user_email: "slovacus@gmail.com"
          commit_author: "slovacus <slovacus@gmail.com>"